import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import ConditionalFooter from "./components/ConditionalFooter";
import AOSProvider from "./components/AOSProvider";
import LenisProvider from "./components/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], 
  display: 'swap',
});

export const metadata = {
  title: "Hindustan Drones",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-scroll-behavior="smooth"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable}`}
    >
      <body suppressHydrationWarning>
        <LenisProvider />
        <AOSProvider />
        {children}
        <ConditionalFooter />
      </body>
     
    </html>
  );
}